---
version: "3"
services:
  folding-at-home:
    image: stefancrain/folding-at-home:latest
    container_name: folding-at-home
    ports:
      - 7396:7396
    restart: unless-stopped
    command:
      [
        "--user=YOUR_NAME_HERE",
        "--team=229500",
        "--power=full",
        "--gpu-usage=100",
      ]
