---
name: Create Release

on:
  push:
    tags:
      - "*" # Push events to matching *

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    env:
      VERSION: $(cat build/.version)
      VERSION_MAJOR: $(cat build/.version | sed -E 's/\.([^.]*)$//')
      BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Releases ${{ github.ref }} "
          draft: false
          prerelease: false

      - name: Build Container Image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg=VERSION=${{ env.VERSION }} \
            --build-arg=VERSION_MAJOR=${{ env.VERSION_MAJOR }} \
            --build-arg=BUILD_DATE=${{ env.VERSION_MAJOR }} \
            --build-arg=VCS_REF=${{ github.sha }} \
            --tag stefancrain/folding-at-home:latest \
            --tag stefancrain/folding-at-home:${{ env.VERSION }} \
            -f ./build/Dockerfile \
            ./build/ \
            --push
